# Generated by Django 5.1.6 on 2025-03-24 11:33

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiagnosisReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ckd_prediction", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "nifti_image",
                    models.FileField(
                        default=None, upload_to=api.models.report_directory_path
                    ),
                ),
                (
                    "nifti_mask",
                    models.FileField(
                        default=None, upload_to=api.models.report_directory_path
                    ),
                ),
                (
                    "png_image",
                    models.ImageField(
                        default=None, upload_to=api.models.report_directory_path
                    ),
                ),
                (
                    "png_image_overlay",
                    models.ImageField(
                        default=None, upload_to=api.models.report_directory_path
                    ),
                ),
                ("renogram_dict", models.JSONField(blank=True, default=dict)),
                (
                    "grad_cam",
                    models.ImageField(
                        default=None, upload_to=api.models.report_directory_path
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.patient"
                    ),
                ),
            ],
        ),
    ]
