# Generated by Django 5.1.6 on 2025-04-11 09:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosisreport",
            name="dicom_image",
            field=models.ImageField(
                default=None, upload_to=api.models.report_directory_path
            ),
        ),
    ]
