# Generated by Django 5.1.6 on 2025-04-11 10:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_diagnosisreport_dicom_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosisreport",
            name="avgimage1",
            field=models.ImageField(
                default=None, upload_to=api.models.report_directory_path
            ),
        ),
        migrations.AddField(
            model_name="diagnosisreport",
            name="avgimage2",
            field=models.ImageField(
                default=None, upload_to=api.models.report_directory_path
            ),
        ),
        migrations.AddField(
            model_name="diagnosisreport",
            name="avgimage3",
            field=models.ImageField(
                default=None, upload_to=api.models.report_directory_path
            ),
        ),
        migrations.AddField(
            model_name="diagnosisreport",
            name="avgimage4",
            field=models.ImageField(
                default=None, upload_to=api.models.report_directory_path
            ),
        ),
    ]
